version: '3.3'
services:
  transdb:
    image: postgres:13
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - transnet
    volumes:
      - mydb:/var/lib/postgresql/data
networks:
  transnet:

volumes:
  mydb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ysay/devdb
