version: "3.3"

services:
  db:
    image: postgres:13
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - transnet
    volumes:
      - trdb:/var/lib/postgresql/data

  backend:
    image: backend
    build: ./backend
    container_name: backend
    ports:
      - 3334:3334
      - 5555:5555
    networks:
      - transnet
    depends_on:
      - db

  frontend:
    image: frontend
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    networks:
      - transnet
    depends_on:
      - db
      - backend

networks:
  transnet:

volumes:
  trdb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/unicorn/devdb
