version: "3.3"

networks:
  app_net:
   driver: bridge

services:
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - app_net
    volumes:
      - trdb:/var/lib/postgresql/data
    networks:
      - app_net
    restart: unless-stopped

  app:
    build: ./
    container_name: app
    restart: unless-stopped
    networks:
     - app_net
    ports:
     - 3000:3000
     - 3334:3334
    depends_on:
     - db

volumes:
  trdb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/devdb
