version: '3.3'

services:
  transdb:
    image: postgres:13
    container_name: db
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - transnet
    volumes:
      - trdb:/var/lib/postgresql/data

  backend:
    image: backend
    build: ./backend
    container_name: backend
    ports:
        - 3334:3334
    networks:
        - transnet
    depends_on:
        - transdb

  frontend:
    image: frontend
    build: ./frontend
    container_name: frontend
    ports:
        - 3000:3000
        - 5555:3000
    networks:
        - transnet
    depends_on:
        - transdb
        - backend

networks:
  transnet:

volumes:
  trdb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/unicorn/devdb
